program controleFinanceiro;

uses
  Vcl.Forms,
  Vcl.Themes,
  Vcl.Styles,
  attributes.custom in 'library\lib.attributes\attributes.custom.pas',
  attributes.custom.interfaces in 'library\lib.attributes\attributes.custom.interfaces.pas',
  classes.template.cartao in 'library\lib.classes\classes.template.cartao.pas',
  classes.template.conta in 'library\lib.classes\classes.template.conta.pas',
  classes.template.credor in 'library\lib.classes\classes.template.credor.pas',
  classes.template.despesacartao in 'library\lib.classes\classes.template.despesacartao.pas',
  classes.template.interfaces in 'library\lib.classes\classes.template.interfaces.pas',
  classes.template.membrofamilia in 'library\lib.classes\classes.template.membrofamilia.pas',
  classes.template.portador in 'library\lib.classes\classes.template.portador.pas',
  classes.template.saldofgts in 'library\lib.classes\classes.template.saldofgts.pas',
  classes.template.saldoportador in 'library\lib.classes\classes.template.saldoportador.pas',
  classes.template.tags in 'library\lib.classes\classes.template.tags.pas',
  classes.template.unified in 'library\lib.classes\classes.template.unified.pas',
  consts.nomeCadastros in 'library\lib.consts\consts.nomeCadastros.pas',
  consts.SQLs in 'library\lib.consts\consts.SQLs.pas',
  consts.styles in 'library\lib.consts\consts.styles.pas',
  consts.views.forms in 'library\lib.consts\consts.views.forms.pas',
  controller.cadastro in 'cadastros\controllers\controller.cadastro.pas',
  controller.cadastro.interfaces in 'cadastros\controllers\controller.cadastro.interfaces.pas',
  controller.lib in 'library\lib.controllers\controller.lib.pas',
  controller.lib.interfaces in 'library\lib.controllers\controller.lib.interfaces.pas',
  data.cadastro.cartao in 'cadastros\dataModels\data.cadastro.cartao.pas' {dataCadastroCartao: TDataModule},
  data.cadastro.conta in 'cadastros\dataModels\data.cadastro.conta.pas' {dataCadastroConta: TDataModule},
  data.cadastro.credor in 'cadastros\dataModels\data.cadastro.credor.pas' {dataCadastroCredor: TDataModule},
  data.cadastro.despesacartao in 'cadastros\dataModels\data.cadastro.despesacartao.pas' {dataCadastroDespesaCartao: TDataModule},
  data.cadastro.membrofamilia in 'cadastros\dataModels\data.cadastro.membrofamilia.pas' {dataCadastroMembroFamilia: TDataModule},
  data.cadastro.portador in 'cadastros\dataModels\data.cadastro.portador.pas' {dataCadastroPortador: TDataModule},
  data.cadastro.saldoFGTS in 'cadastros\dataModels\data.cadastro.saldoFGTS.pas' {dataCadastroSaldoFGTS: TDataModule},
  data.cadastro.saldoportador in 'cadastros\dataModels\data.cadastro.saldoportador.pas' {dataCadastroSaldoPortador: TDataModule},
  data.cadastro.tags in 'cadastros\dataModels\data.cadastro.tags.pas' {dataCadastroTags: TDataModule},
  data.cadastro.template in 'cadastros\dataModels\template\data.cadastro.template.pas' {dataCadastroTemplate: TDataModule},
  data.images in 'library\lib.images\data.images.pas' {dataImages: TDataModule},
  data.menu in 'menu.principal\dataModel\data.menu.pas' {dataMenu: TDataModule},
  data.realtime.template in 'cadastros\dataModels\template\data.realtime.template.pas' {dataRealTimeTemplate: TDataModule},
  Firebase.Auth in 'library\lib.Firebase\Firebase.Auth.pas',
  Firebase.Database in 'library\lib.Firebase\Firebase.Database.pas',
  Firebase.Interfaces in 'library\lib.Firebase\Firebase.Interfaces.pas',
  Firebase.Request in 'library\lib.Firebase\Firebase.Request.pas',
  Firebase.Response in 'library\lib.Firebase\Firebase.Response.pas',
  lib.conexao.db.interfaces in 'library\lib.conexao.db\lib.conexao.db.interfaces.pas',
  lib.conexao.factory in 'library\lib.conexao.db\lib.conexao.factory.pas',
  lib.DAO.conexao in 'library\lib.conexao.db\lib.DAO.conexao.pas',
  lib.DAO.conexao.config in 'library\lib.conexao.db\lib.DAO.conexao.config.pas',
  lib.DAO.dataModel in 'library\lib.DAO\lib.DAO.dataModel.pas' {dmConexaoDB: TDataModule},
  lib.helper.querys in 'library\lib.helpers\lib.helper.querys.pas',
  lib.login.realtimedb in 'library\lib.conexao.db\lib.login.realtimedb.pas',
  lib.login.realtimedb.config in 'library\lib.conexao.db\lib.login.realtimedb.config.pas',
  lib.login.view in 'library\lib.login\lib.login.view.pas' {fLoginView},
  lib.observer in 'library\lib.observer\lib.observer.pas',
  lib.proc.objects in 'library\lib.proc.objects\lib.proc.objects.pas',
  lib.RT.conexao in 'library\lib.conexao.db\lib.RT.conexao.pas',
  lib.sql.interfaces in 'library\lib.SQL\lib.sql.interfaces.pas',
  lib.sql.resumomenu in 'library\lib.SQL\lib.sql.resumomenu.pas',
  lib.types.enum in 'library\lib.types\lib.types.enum.pas',
  model.cadastro.abstract in 'cadastros\models\template\model.cadastro.abstract.pas',
  model.cadastro.campos in 'cadastros\models\template\model.cadastro.campos.pas',
  model.cadastro.cartao in 'cadastros\models\model.cadastro.cartao.pas',
  model.cadastro.conta in 'cadastros\models\model.cadastro.conta.pas',
  model.cadastro.credor in 'cadastros\models\model.cadastro.credor.pas',
  model.cadastro.despesacartao in 'cadastros\models\model.cadastro.despesacartao.pas',
  model.cadastro.factory in 'cadastros\models\template\model.cadastro.factory.pas',
  model.cadastro.interfaces in 'cadastros\models\template\model.cadastro.interfaces.pas',
  model.cadastro.jsonstring in 'cadastros\models\template\model.cadastro.jsonstring.pas',
  model.cadastro.membrofamilia in 'cadastros\models\model.cadastro.membrofamilia.pas',
  model.cadastro.portador in 'cadastros\models\model.cadastro.portador.pas',
  model.cadastro.saldofgts in 'cadastros\models\model.cadastro.saldofgts.pas',
  model.cadastro.saldoportador in 'cadastros\models\model.cadastro.saldoportador.pas',
  model.cadastro.tags in 'cadastros\models\model.cadastro.tags.pas',
  model.lib in 'library\lib.models\model.lib.pas',
  model.lib.aguarde in 'library\lib.models\model.lib.aguarde.pas',
  model.lib.interfaces in 'library\lib.models\model.lib.interfaces.pas',
  pkg.json.interfaces in 'library\lib.pkg.JSON\pkg.json.interfaces.pas',
  pkg.json.template in 'library\lib.pkg.JSON\pkg.json.template.pas',
  view.aguarde in 'library\lib.view.geral\view.aguarde.pas' {formLibAguarde},
  view.cadastro.cartao in 'cadastros\views\view.cadastro.cartao.pas' {formCadCartao},
  view.cadastro.conta in 'cadastros\views\view.cadastro.conta.pas' {formCadConta},
  view.cadastro.credor in 'cadastros\views\view.cadastro.credor.pas' {formCadCredor},
  view.cadastro.despesacartao in 'cadastros\views\view.cadastro.despesacartao.pas' {formCadDespesaCartao},
  view.cadastro.membrofamilia in 'cadastros\views\view.cadastro.membrofamilia.pas' {formCadMembroFamilia},
  view.cadastro.saldofgts in 'cadastros\views\view.cadastro.saldofgts.pas' {formCadSaldoFGTS},
  view.cadastro.saldoportador in 'cadastros\views\view.cadastro.saldoportador.pas' {formCadSaldoPortador},
  view.cadastro.tags in 'cadastros\views\view.cadastro.tags.pas' {formCadTags},
  view.cadastro.template in 'cadastros\views\template\view.cadastro.template.pas' {formCadastroTemplate},
  view.geral in 'library\lib.view.geral\view.geral.pas' {formTemplate},
  view.menu in 'menu.principal\view.menu.pas' {formMenu},
  lib.records in 'library\lib.records\lib.records.pas',
  model.cadastro.conta.pagar in 'cadastros\models\model.cadastro.conta.pagar.pas',
  view.cadastro.conta.pagar in 'cadastros\views\view.cadastro.conta.pagar.pas' {formCadContaPagar},
  data.cadastro.conta.pagar in 'cadastros\dataModels\data.cadastro.conta.pagar.pas' {dataCadastroContaPagar: TDataModule},
  model.cadastro.conta.receber in 'cadastros\models\model.cadastro.conta.receber.pas',
  data.cadastro.conta.receber in 'cadastros\dataModels\data.cadastro.conta.receber.pas' {dataCadastroContaReceber: TDataModule},
  consts.imagens in 'library\lib.consts\consts.imagens.pas',
  view.cadastro.conta.receber in 'cadastros\views\view.cadastro.conta.receber.pas' {formCadContaReceber},
  data.images.interfaces in 'library\lib.images\data.images.interfaces.pas',
  lib.helper.dictionary in 'library\lib.helpers\lib.helper.dictionary.pas',
  frame.menu in 'menu.principal\frame\frame.menu.pas' {frameMenu: TFrame},
  data.cadastro.template.interfaces in 'cadastros\dataModels\template\data.cadastro.template.interfaces.pas',
  lib.messages in 'library\lib.messages\lib.messages.pas',
  lib.messages.interfaces in 'library\lib.messages\lib.messages.interfaces.pas',
  data.cadastro.template.factory in 'cadastros\dataModels\template\data.cadastro.template.factory.pas',
  view.cadastro.portador in 'cadastros\views\view.cadastro.portador.pas' {formCadPortador},
  frame.cadastro.conta in 'cadastros\views\frames\frame.cadastro.conta.pas' {frameCadConta: TFrame},
  lib.sql.geral in 'library\lib.SQL\lib.sql.geral.pas',
  frame.cadastro.saldoportador in 'cadastros\views\frames\frame.cadastro.saldoportador.pas' {frameCadSaldoPortador: TFrame},
  data.frame.cadastro.template in 'cadastros\dataModels\frames\data.frame.cadastro.template.pas' {dmFrameGrade: TDataModule},
  data.frame.cadastro.conta in 'cadastros\dataModels\frames\data.frame.cadastro.conta.pas' {dmFrameConta: TDataModule},
  data.frame.cadastro.saldoportador in 'cadastros\dataModels\frames\data.frame.cadastro.saldoportador.pas' {dmFrameSaldoPortador: TDataModule},
  view.relatorio.factory in 'relatorios\views\view.relatorio.factory.pas',
  view.relatorio.saldodetalhadoportador in 'relatorios\views\view.relatorio.saldodetalhadoportador.pas' {formSaldoDetalhadoPortador},
  model.relatorio.saldodetalhadoportador in 'relatorios\models\model.relatorio.saldodetalhadoportador.pas' {dmSaldoDetalhadoPortador: TDataModule},
  frame.cadastro.conta.imgs in 'cadastros\views\frames\frame.cadastro.conta.imgs.pas' {frameCadContaImagens: TFrame},
  lib.view.splash in 'library\lib.splash\lib.view.splash.pas' {formSplash},
  lib.sql.splash in 'library\lib.SQL\lib.sql.splash.pas',
  lib.data.splash in 'library\lib.splash\lib.data.splash.pas' {dataSplash: TDataModule},
  lib.DAO.comandosTransacao in 'library\lib.DAO\lib.DAO.comandosTransacao.pas' {dmCmdTransacao: TDataModule},
  lib.DAO.interfaces in 'library\lib.DAO\lib.DAO.interfaces.pas',
  lib.sql.contapagamento in 'library\lib.SQL\lib.sql.contapagamento.pas',
  view.cadastro.saldoportador.transferencia in 'cadastros\views\view.cadastro.saldoportador.transferencia.pas' {formSaldoPortadorTransferencia},
  lib.sql.lookup in 'library\lib.SQL\lib.sql.lookup.pas',
  data.cadastro.saldoportador.transferencia in 'cadastros\dataModels\data.cadastro.saldoportador.transferencia.pas' {dataCadastroSaldoPortadorTransferencia: TDataModule},
  view.relatorio.saldodetalhadoportador.grafico in 'relatorios\views\view.relatorio.saldodetalhadoportador.grafico.pas' {formSaldoDetalhadoPortadorGrafico},
  model.relatorio.saldodetalhadoportador.grafico in 'relatorios\models\model.relatorio.saldodetalhadoportador.grafico.pas' {dmSaldoDetalhadoPortadorGrafico: TDataModule},
  view.aluguel.factory in 'alugueis\views\view.aluguel.factory.pas',
  view.aluguel.lancamento in 'alugueis\views\view.aluguel.lancamento.pas' {formAluguelLancamento},
  frame.aluguel.lancamento in 'alugueis\frame\frame.aluguel.lancamento.pas' {frameAluguelLancamento: TFrame},
  data.aluguel.lancamento in 'alugueis\dataModel\data.aluguel.lancamento.pas' {dataAluguel: TDataModule},
  lib.sql.alugueis in 'library\lib.SQL\lib.sql.alugueis.pas',
  view.calcular in 'cadastros\views\view.calcular\view.calcular.pas' {formCalcular},
  view.aluguel.editor in 'alugueis\views\view.aluguel.editor.pas' {formAluguelEditor},
  view.relatorio.saldoextrato in 'relatorios\views\view.relatorio.saldoextrato.pas' {formSaldoExtrato},
  model.relatorio.saldoextrato in 'relatorios\models\model.relatorio.saldoextrato.pas' {dmSaldoExtrato: TDataModule};

{$R *.res}

begin
  Application.Initialize;
  {$IFDEF DEBUG}
    ReportMemoryLeaksOnShutdown := True;
  {$ENDIF}
  Application.MainFormOnTaskbar := True;
  TStyleManager.TrySetStyle('Silver');
  Application.Title := 'Controle Financeiro';
  if TfLoginView.ConectarAoSistema then
    Application.CreateForm(TformMenu, formMenu);
  Application.Run;
end.
